name: Unzip File

on:
  push:
    paths:
      - "*.zip"  # Trigger saat file ZIP di-upload.

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract ZIP
        run: |
          for file in *.zip; do
            unzip "$file" -d "${file%.zip}"
          done
